#!/usr/bin/env python3
"""Regenerate the reference section of the MkDocs site from code.

Outputs four pages under docs/site/reference/:

  cli.md           — every CLI command with its help text
  handlers.md      — handler/subtype inventory grouped by category
  schemas.md       — schema list with tag counts and subtype mappings
  output-formats.md— output format catalog (CLI + Python API)

The script is hermetic: it imports the package, introspects, and writes
markdown. Re-run after any change to the CLI, handler set, or schema YAMLs
and commit the diff.

Usage:
    uv run python scripts/build_docs_reference.py
"""

from __future__ import annotations

from pathlib import Path

import click

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "site" / "reference"

HEADER_AUTO = (
    "<!-- Autogenerated by scripts/build_docs_reference.py — do not edit by hand. -->\n\n"
)


# ── CLI reference ────────────────────────────────────────────────────────────

def generate_cli_md() -> None:
    from synterr.cli import main as cli_root

    lines: list[str] = [
        HEADER_AUTO,
        "# CLI reference\n\n",
        "Every `synterr` command with its full help text. Re-run "
        "`uv run synterr <command> --help` to see the same thing locally.\n\n",
    ]

    ctx_root = click.Context(cli_root, info_name="synterr")
    lines.append("## `synterr`\n\n")
    lines.append("```\n")
    lines.append(cli_root.get_help(ctx_root))
    lines.append("\n```\n\n")

    for name in sorted(cli_root.commands.keys()):
        cmd = cli_root.commands[name]
        if cmd.hidden:
            continue  # compat aliases stay callable but undocumented
        ctx = click.Context(cmd, info_name=f"synterr {name}", parent=ctx_root)
        short = (cmd.short_help or "").strip()
        lines.append(f"## `synterr {name}`\n\n")
        if short:
            lines.append(f"{short}\n\n")
        lines.append("```\n")
        lines.append(cmd.get_help(ctx))
        lines.append("\n```\n\n")

    (OUT / "cli.md").write_text("".join(lines), encoding="utf-8")


# ── Handlers / subtypes ──────────────────────────────────────────────────────

def generate_handlers_md() -> None:
    from synterr.languages.russian.errors import get_all_handlers

    handlers = get_all_handlers()
    by_cat: dict[str, list] = {}
    for h in handlers:
        by_cat.setdefault(h.category, []).append(h)

    total_subtypes = sum(len(h.subtypes) for h in handlers)

    lines: list[str] = [
        HEADER_AUTO,
        "# Handlers and subtypes\n\n",
        f"**{len(handlers)} handlers, {total_subtypes} subtypes** across "
        f"{len(by_cat)} categories. Source of truth: "
        f"`src/synterr/languages/russian/errors/`.\n\n",
        "Categories: ",
        ", ".join(f"`{c}`" for c in sorted(by_cat.keys())),
        ".\n\n",
        "| Handler | Subtypes | Category | Length-changing |\n",
        "|---|---|---|---|\n",
    ]
    for cat in sorted(by_cat.keys()):
        for h in sorted(by_cat[cat], key=lambda x: x.name):
            subtypes_cell = ", ".join(f"`{s}`" for s in h.subtypes)
            length = "yes" if getattr(h, "changes_length", False) else "no"
            lines.append(
                f"| `{h.name}` | {subtypes_cell} | `{h.category}` | {length} |\n"
            )
    lines.append("\n")

    # Per-category breakdown with prose
    for cat in sorted(by_cat.keys()):
        lines.append(f"\n## {cat}\n\n")
        for h in sorted(by_cat[cat], key=lambda x: x.name):
            lines.append(
                f"### `{h.name}` ({len(h.subtypes)} subtype{'s' if len(h.subtypes) != 1 else ''})\n\n"
            )
            doc = (h.__class__.__doc__ or "").strip().split("\n")[0]
            if doc:
                lines.append(f"{doc}\n\n")
            for s in h.subtypes:
                lines.append(f"- `{h.name}:{s}`\n")
            lines.append("\n")

    (OUT / "handlers.md").write_text("".join(lines), encoding="utf-8")


# ── Schemas ──────────────────────────────────────────────────────────────────

def generate_schemas_md() -> None:
    from synterr.languages.russian.errors import get_all_handlers
    from synterr.schemas import get_default_schema, list_schemas, load_schema

    handlers = get_all_handlers()
    available_subtypes = set()
    for h in handlers:
        available_subtypes.update(h.subtypes)

    default = get_default_schema()
    schemas = sorted(list_schemas())

    lines: list[str] = [
        HEADER_AUTO,
        "# Schemas\n\n",
        f"Synterr ships **{len(schemas)} schemas**. Default: `{default}`. "
        "Schemas live in `src/synterr/schemas/data/`.\n\n",
        "| Schema | Tags | Description |\n",
        "|---|---|---|\n",
    ]
    for name in schemas:
        try:
            s = load_schema(name)
            marker = " *(default)*" if name == default else ""
            lines.append(
                f"| `{name}`{marker} | {len(s.tags)} | {s.description.strip()} |\n"
            )
        except Exception as e:
            lines.append(f"| `{name}` | ? | (load error: {e!r}) |\n")
    lines.append("\n")

    # Coverage per schema
    for name in schemas:
        try:
            s = load_schema(name)
        except Exception:
            continue
        report = s.get_coverage_report(available_subtypes)
        lines.append(f"\n## `{name}`\n\n")
        lines.append(f"{s.description.strip()}\n\n")
        lines.append(
            f"**Coverage:** {report['covered_tags']}/{report['total_tags']} "
            f"tags mapped ({report['coverage_percent']}%).\n\n"
        )
        if report["covered_tag_names"]:
            lines.append("### Covered tags\n\n")
            for t in report["covered_tag_names"]:
                lines.append(f"- `{t}`\n")
            lines.append("\n")
        if report["uncovered_tag_names"]:
            lines.append("### Uncovered tags\n\n")
            for t in report["uncovered_tag_names"]:
                lines.append(f"- `{t}`\n")
            lines.append("\n")

    (OUT / "schemas.md").write_text("".join(lines), encoding="utf-8")


# ── Output formats ───────────────────────────────────────────────────────────

def generate_output_formats_md() -> None:
    from synterr.cli import main as cli_root

    # Discover formats from the `generate` command's --output-format choice
    formats = []
    gen = cli_root.commands.get("generate")
    if gen is not None:
        for p in gen.params:
            if getattr(p, "name", "") == "output_format":
                tp = getattr(p, "type", None)
                if hasattr(tp, "choices"):
                    formats = list(tp.choices)
                break

    lines: list[str] = [
        HEADER_AUTO,
        "# Output formats\n\n",
        "Synterr emits corrupted text in several formats. CLI selection is "
        "via the `-f`/`--output-format` flag on `synterr generate`.\n\n",
        "## CLI formats\n\n",
        "| Flag | When to use |\n",
        "|---|---|\n",
    ]

    descriptions = {
        "gector": "GECToR token-level edit tags (default). Compatible with the GECToR training format.",
        "tsv": "Parallel `src\\ttgt` lines. Compatible with most seq2seq pipelines.",
        "jsonl": "Rich JSON per line: `src`, `tgt`, `errors[]` with type/category/schema_tag/schema_l2_tag.",
        "chat": "Instruction-tuning chat format (`messages: [...]`). For QLoRA / SFT fine-tuning of chat LLMs.",
        "sft": "Minimal `{src, tgt}` JSONL. Compatible with standard SFT trainers.",
    }
    for f in formats:
        lines.append(f"| `{f}` | {descriptions.get(f, '_(undocumented)_')} |\n")
    lines.append("\n")

    lines.append("## Python API\n\n")
    lines.append(
        "Beyond the CLI, the `GeneratedResult` object on `pipeline.generate()` "
        "exposes:\n\n"
        "- `result.formatted` — GECToR token-level tags (string).\n"
        "- `result.to_tsv()` — parallel src/tgt.\n"
        "- `result.to_jsonl()` — rich per-record JSON.\n"
        "- `result.to_chat()` — instruction-tuning chat format.\n"
        "- `result.to_diff()` — human-readable inline diff (CLI-unexposed).\n\n"
    )
    lines.append("## Rule-targeted SFT\n\n")
    lines.append(
        "The separate `synterr generate-targeted` command writes "
        "`{src, tgt, rule}` JSONL with one line per LoRuGEC rule "
        "force-applied. A `.dist.json` sidecar records the per-rule "
        "generation count. See `synterr.sft.generate_targeted` for the "
        "Python API.\n"
    )

    (OUT / "output-formats.md").write_text("".join(lines), encoding="utf-8")


# ── Reference index ──────────────────────────────────────────────────────────

def generate_index_md() -> None:
    lines: list[str] = [
        HEADER_AUTO,
        "# Reference\n\n",
        "Auto-generated reference pages, kept in sync with the code by\n"
        "`scripts/build_docs_reference.py`.\n\n",
        "- [CLI reference](cli.md) — every `synterr` command and its help text.\n",
        "- [Handlers and subtypes](handlers.md) — the full handler/subtype inventory grouped by category.\n",
        "- [Schemas](schemas.md) — schemas shipped, tag counts, per-schema coverage by current handlers.\n",
        "- [Output formats](output-formats.md) — CLI and Python API output options.\n\n",
        "For conceptual orientation see [Architecture](../architecture.md); "
        "for extension points see [Extending synterr](../extending.md).\n",
    ]
    (OUT / "index.md").write_text("".join(lines), encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    print(f"writing reference pages under {OUT.relative_to(ROOT)}/")
    generate_cli_md();           print("  cli.md")
    generate_handlers_md();      print("  handlers.md")
    generate_schemas_md();       print("  schemas.md")
    generate_output_formats_md();print("  output-formats.md")
    generate_index_md();         print("  index.md")
    print("done.")


if __name__ == "__main__":
    main()
